[package]
name = "dwarf_land"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0" }
bevy-inspector-egui = "0.23.4"
rand = "0.8.5"
smooth-bevy-cameras = "0.11.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
